### ISSUE TITLE
Port 7883

### ISSUE THREAD

**Issue by rajil** [heikomat/element-call-traefik#1]
Port 7883 is not mentioned at https://docs.livekit.io/home/self-hosting/ports-firewall/. Did you mean 7882?

**Comment by heikomat** [comment]
You are correct, good catch!
In my own deployment port 7882 is used. Must've been a typo. I will fix that shortly :)

**Comment by heikomat** [comment]
I've [updated the readme](https://github.com/heikomat/element-call-traefik/commit).

If you also think this solves the issue feel free to close it. If not, let me know.
